version: '3.8'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/ephe:/app/ephe
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
