services:
  - type: web
    name: meridian-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: FLASK_ENV
        value: 'production'
  - type: web
    name: meridian-front
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: 'https://meridian-api.onrender.com'
