services:
  # Full-stack service (serves both API and frontend)
  - type: web
    name: meridian-v2
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    port: 5000
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: FLASK_ENV
        value: 'production'
      - key: PORT
        value: '5000'
