services:
  # Full-stack service (serves both API and frontend)
  - type: web
    name: meridian-v2
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: FLASK_ENV
        value: 'production'
      - key: PORT
        value: '5000'
      - key: VITE_GEOAPIFY_API_KEY
        value: 89b7ba6d03ca4cfc871fac9f5d3dade0
